#! /bin/bash

# Change the G_DICTIONARY_PATH variable to wherever you have the code
install_dir="$(pwd)"
sed_exp="s:G_DICTIONARY_PATH=\"/home/\$USER/Documents/code/g\":G_DICTIONARY_PATH=$install_dir:"
cat g.sh | sed $sed_exp > g_temp
mv g_temp g.sh

# load the file when bash starts up
cd
echo "# load g" >> .bashrc
echo "source $install_dir/g.sh" >> .bashrc

# clear the dictionary (I assume you don't care about my shortcuts)
cd $install_dir
rm dictionary.txt
touch dictionary.txt
